### ISSUE TITLE
ToDo project setup

### ISSUE THREAD

**Issue by realDragonium** [JessePol/speedsheet#1]
### Setup
- [ ] Setup typescript
- [ ] Setup tests
- [ ] Make sure code is only ESM? (svelte approves this)
- [ ] Setup github actions
- [ ] Setup linter which is enforced/checked
- [ ] Write simple roadmap
- [ ] Write simple readme
- [ ] find library for data graphs
- [ ] Setup github project

### Code:
- [ ] #3
- [ ] Prevent framework specific library 'locks' (so that anyone could use it no matter which framework they're using)
- [ ] Make UI configurable

### NextUps:
- [ ] Replace core with webassembly for real speed 🚀 
- [ ] Look into making own data graphs
